# 체육시설 데이터 전처리

## 프로젝트 개요

01단계에서 Selenium을 이용하여 수집한
서울시 체육시설 공공서비스예약 데이터를 불러와
Pandas를 이용하여 전처리를 수행한다.

### 전처리 과정

1. 원본 데이터 불러오기
2. 데이터 구조 및 기본 정보 확인
3. 결측치 확인
4. 중복 데이터 확인 및 제거
5. 문자열 데이터 정리
6. 전처리 결과 확인
7. 최종 데이터 저장

In [1]:
import pandas as pd

In [10]:
# 원본 크롤링 데이터 불러오기
input_file = 'sports_crawling_raw.csv'

df = pd.read_csv(
    input_file,
    encoding='utf-8-sig'
)

print('원본 데이터 불러오기 완료')
print('데이터 크기:', df.shape)

원본 데이터 불러오기 완료
데이터 크기: (18, 6)

## 데이터 기본 정보 확인

크롤링한 원본 데이터의 행과 열,
컬럼명 및 데이터 타입을 확인한다.

In [4]:
# 데이터 앞부분 확인
display(df.head())

,서비스구분,서비스ID,대분류명,소분류명,서비스상태,서비스명
0,자체,S251121100349891778,체육시설,테니스장,접수중,테니스장1(평일)-2026년 응봉공원(대현산배수지)
1,자체,S251121102355938084,체육시설,테니스장,접수중,테니스장1(토/일/공휴일)-2026년 응봉공원(대현산배수지)
2,자체,S251121103012746640,체육시설,테니스장,접수중,테니스장2(평일)-2026년 응봉공원(대현산배수지)
3,자체,S251121103347587479,체육시설,테니스장,접수중,테니스장2(토/일/공휴일)-2026년 응봉공원(대현산배수지)
4,자체,S251121103722953401,체육시설,다목적경기장,접수중,다목적구장-2026년 응봉공원(대현산배수지)

In [11]:
# 데이터 크기 확인
print('행 개수:', df.shape[0])
print('열 개수:', df.shape[1])

행 개수: 18
열 개수: 6

In [12]:
# 컬럼명 확인
print('컬럼 목록')

for i, column in enumerate(df.columns):
    print(f"{i}. {column}")

컬럼 목록
0. 서비스구분
1. 서비스ID
2. 대분류명
3. 소분류명
4. 서비스상태
5. 서비스명

In [7]:
# 데이터 타입 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   서비스구분   18 non-null     str
 1   서비스ID   18 non-null     str
 2   대분류명    18 non-null     str
 3   소분류명    18 non-null     str
 4   서비스상태   18 non-null     str
 5   서비스명    18 non-null     str
dtypes: str(6)
memory usage: 996.0 bytes

## 결측치 확인 및 처리

각 컬럼별 결측치 개수를 확인하고,
필요한 경우 결측 데이터를 처리한다.

In [8]:
# 컬럼별 결측치 확인
missing = df.isnull().sum()

print('컬럼별 결측치')
display(missing.to_frame('결측치 개수'))

컬럼별 결측치

       결측치 개수
서비스구분       0
서비스ID       0
대분류명        0
소분류명        0
서비스상태       0
서비스명        0

In [13]:
# 전체 결측치 개수
print('전체 결측치:', df.isnull().sum().sum())

전체 결측치: 0

## 중복 데이터 확인 및 제거

동일한 데이터가 여러 번 수집되었는지 확인하고,
중복 데이터가 존재할 경우 제거한다.

서비스ID를 기준으로 데이터의 고유성을 확인한다.

In [14]:
# 전체 행 기준 중복 확인
duplicate_count = df.duplicated().sum()

print('전체 행 중복 데이터:', duplicate_count, '건')

전체 행 중복 데이터: 0 건

In [15]:
# 서비스ID 중복 확인
service_id_duplicate = df['서비스ID'].duplicated().sum()

print('서비스ID 중복 데이터:', service_id_duplicate, '건')

서비스ID 중복 데이터: 0 건

In [16]:
# 서비스ID 기준 중복 제거
df = df.drop_duplicates(
    subset=['서비스ID'],
    keep='first'
)

print('중복 제거 후 데이터:', len(df), '건')

중복 제거 후 데이터: 18 건

## 문자열 데이터 정리

서비스명 및 분류 정보에 포함될 수 있는
불필요한 앞뒤 공백을 제거한다.

In [17]:
# 문자열 컬럼의 앞뒤 공백 제거
text_columns = [
    '서비스구분',
    '서비스ID',
    '대분류명',
    '소분류명',
    '서비스상태',
    '서비스명'
]

for column in text_columns:
    df[column] = df[column].astype(str).str.strip()

print('문자열 데이터 정리 완료')

문자열 데이터 정리 완료

In [18]:
# 빈 문자열 확인
for column in text_columns:
    empty_count = (df[column] == '').sum()
    
    if empty_count > 0:
        print(f'{column}: {empty_count}건')

In [19]:
# 서비스 상태별 데이터 개수
status_count = df['서비스상태'].value_counts()

print('서비스 상태별 데이터 개수')
display(status_count)

서비스 상태별 데이터 개수

서비스상태
접수종료    11
접수중      7
Name: count, dtype: int64

## 전처리 결과 확인

모든 전처리 작업이 완료된 데이터를 확인한다.

In [20]:
# 최종 데이터 확인
print('최종 데이터 크기:', df.shape)

display(df)

최종 데이터 크기: (18, 6)

,서비스구분,서비스ID,대분류명,소분류명,서비스상태,서비스명
0,자체,S251121100349891778,체육시설,테니스장,접수중,테니스장1(평일)-2026년 응봉공원(대현산배수지)
1,자체,S251121102355938084,체육시설,테니스장,접수중,테니스장1(토/일/공휴일)-2026년 응봉공원(대현산배수지)
2,자체,S251121103012746640,체육시설,테니스장,접수중,테니스장2(평일)-2026년 응봉공원(대현산배수지)
3,자체,S251121103347587479,체육시설,테니스장,접수중,테니스장2(토/일/공휴일)-2026년 응봉공원(대현산배수지)
4,자체,S251121103722953401,체육시설,다목적경기장,접수중,다목적구장-2026년 응봉공원(대현산배수지)
5,자체,S210401100008601453,체육시설,축구장,접수종료,○ [평일] (주간) 마포 난지천 인조잔디축구장
6,자체,S260706132614891677,체육시설,풋살장,접수중,8월 [평일]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수
7,자체,S260706134128763150,체육시설,풋살장,접수중,8월 [공휴일주말]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수
8,자체,S241210095552925088,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
9,자체,S241210100011131040,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
10,자체,S241210100257966783,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
11,자체,S241210100509852746,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)
12,자체,S241210100804518772,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(주간사용)
13,자체,S241210100945082970,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(조기사용)
14,자체,S250113101314920195,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
15,자체,S250113101640215242,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
16,자체,S250113101818758665,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
17,자체,S250113102023294415,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)

In [21]:
# 최종 결측치 확인

print('최종 결측치:', df.isnull().sum().sum())

최종 결측치: 0

In [22]:
# 최종 중복 확인
print('최종 중복 데이터:', df.duplicated().sum())

최종 중복 데이터: 0

## 전처리 데이터 저장

전처리가 완료된 데이터를 CSV 파일로 저장한다.

저장된 파일은 다음 단계에서 MySQL 데이터베이스에
저장하기 위한 입력 데이터로 사용한다.

In [24]:
# 전처리 완료 데이터 저장
output_file = 'sports_crawling_raw.csv'

df.to_csv(
    output_file,
    index=False,
    encoding='utf-8-sig'
)

print('전처리 데이터 저장 완료')
print('파일명:', output_file)
print('저장 데이터:', len(df), '건')

전처리 데이터 저장 완료
파일명: sports_crawling_raw.csv
저장 데이터: 18 건