# 데이터베이스 저장

## 프로젝트 개요

02단계에서 전처리한 체육시설 데이터를
MySQL 데이터베이스에 저장한다.

### 데이터 저장 과정

1. 전처리 데이터 불러오기
2. MySQL 연결
3. 데이터베이스 생성
4. 테이블 생성
5. 데이터 저장
6. 저장 결과 확인

In [4]:
import os
import pandas as pd
import mysql.connector

from dotenv import load_dotenv

## 전처리 데이터 불러오기

02단계에서 전처리한 CSV 파일을 불러온다.

In [3]:
# 전처리 데이터 불러오기
input_file = 'sports_crawling_raw.csv'

df = pd.read_csv(
    input_file,
    encoding='utf-8-sig'
)

print('데이터 불러오기 완료')
print('데이터 크기:', df.shape)

display(df)

데이터 불러오기 완료
데이터 크기: (18, 6)

,서비스구분,서비스ID,대분류명,소분류명,서비스상태,서비스명
0,자체,S251121100349891778,체육시설,테니스장,접수중,테니스장1(평일)-2026년 응봉공원(대현산배수지)
1,자체,S251121102355938084,체육시설,테니스장,접수중,테니스장1(토/일/공휴일)-2026년 응봉공원(대현산배수지)
2,자체,S251121103012746640,체육시설,테니스장,접수중,테니스장2(평일)-2026년 응봉공원(대현산배수지)
3,자체,S251121103347587479,체육시설,테니스장,접수중,테니스장2(토/일/공휴일)-2026년 응봉공원(대현산배수지)
4,자체,S251121103722953401,체육시설,다목적경기장,접수중,다목적구장-2026년 응봉공원(대현산배수지)
5,자체,S210401100008601453,체육시설,축구장,접수종료,○ [평일] (주간) 마포 난지천 인조잔디축구장
6,자체,S260706132614891677,체육시설,풋살장,접수중,8월 [평일]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수
7,자체,S260706134128763150,체육시설,풋살장,접수중,8월 [공휴일주말]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수
8,자체,S241210095552925088,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
9,자체,S241210100011131040,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
10,자체,S241210100257966783,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
11,자체,S241210100509852746,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)
12,자체,S241210100804518772,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(주간사용)
13,자체,S241210100945082970,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(조기사용)
14,자체,S250113101314920195,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
15,자체,S250113101640215242,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
16,자체,S250113101818758665,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
17,자체,S250113102023294415,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)

## MySQL 서버 연결

.env 파일에 저장된 데이터베이스 접속 정보를 이용하여
MySQL 서버에 연결한다.

In [9]:
# MySQL 서버 연결
conn = mysql.connector.connect(
    host=DB_HOST,
    user=DB_USER,
    password=DB_PASSWORD
)

cursor = conn.cursor()

print('MySQL 연결 성공')

MySQL 연결 성공

## 데이터베이스 생성

체육시설 크롤링 데이터를 저장하기 위한
데이터베이스를 생성한다.

데이터베이스 이름은 .env 파일의 DB_NAME 값을 사용한다.

In [10]:
# 데이터베이스 생성
cursor.execute(
    f'CREATE DATABASE IF NOT EXISTS {DB_NAME}'
)

print('데이터베이스 생성 완료:', DB_NAME)

데이터베이스 생성 완료: sports_crawling

In [11]:
# 사용할 데이터베이스 선택
conn.database = DB_NAME

print('사용 데이터베이스:', DB_NAME)

사용 데이터베이스: sports_crawling

## 체육시설 테이블 생성

전처리된 체육시설 데이터를 저장하기 위한
sports_facility 테이블을 생성한다.

서비스ID는 각 체육시설 서비스를 구분하는
고유 식별자로 사용한다.

In [12]:
# 테이블 생성

table_name = 'sports_facility'

create_table_sql = f'''
CREATE TABLE IF NOT EXISTS {table_name} (
    서비스구분 VARCHAR(20),
    서비스ID VARCHAR(30) PRIMARY KEY,
    대분류명 VARCHAR(50),
    소분류명 VARCHAR(50),
    서비스상태 VARCHAR(20),
    서비스명 VARCHAR(500)
)
'''

cursor.execute(create_table_sql)

print('테이블 생성 완료:', table_name)

테이블 생성 완료: sports_facility

## 전처리 데이터 불러오기

02단계에서 생성한 전처리 완료 데이터를
Pandas DataFrame으로 불러온다.

In [14]:
# 전처리 데이터 불러오기
input_file = 'sports_crawling_raw.csv'

df = pd.read_csv(
    input_file,
    encoding='utf-8-sig'
)

print('전처리 데이터 불러오기 완료')
print('데이터 크기:', df.shape)

display(df)

전처리 데이터 불러오기 완료
데이터 크기: (18, 6)

,서비스구분,서비스ID,대분류명,소분류명,서비스상태,서비스명
0,자체,S251121100349891778,체육시설,테니스장,접수중,테니스장1(평일)-2026년 응봉공원(대현산배수지)
1,자체,S251121102355938084,체육시설,테니스장,접수중,테니스장1(토/일/공휴일)-2026년 응봉공원(대현산배수지)
2,자체,S251121103012746640,체육시설,테니스장,접수중,테니스장2(평일)-2026년 응봉공원(대현산배수지)
3,자체,S251121103347587479,체육시설,테니스장,접수중,테니스장2(토/일/공휴일)-2026년 응봉공원(대현산배수지)
4,자체,S251121103722953401,체육시설,다목적경기장,접수중,다목적구장-2026년 응봉공원(대현산배수지)
5,자체,S210401100008601453,체육시설,축구장,접수종료,○ [평일] (주간) 마포 난지천 인조잔디축구장
6,자체,S260706132614891677,체육시설,풋살장,접수중,8월 [평일]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수
7,자체,S260706134128763150,체육시설,풋살장,접수중,8월 [공휴일주말]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수
8,자체,S241210095552925088,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
9,자체,S241210100011131040,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
10,자체,S241210100257966783,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
11,자체,S241210100509852746,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)
12,자체,S241210100804518772,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(주간사용)
13,자체,S241210100945082970,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(조기사용)
14,자체,S250113101314920195,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
15,자체,S250113101640215242,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
16,자체,S250113101818758665,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
17,자체,S250113102023294415,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)

## 체육시설 데이터 저장

Pandas DataFrame에 저장된 전처리 데이터를
MySQL의 sports_facility 테이블에 저장한다.

In [16]:
# 데이터 저장 SQL
insert_sql = f'''
INSERT INTO {table_name}
(
    서비스구분,
    서비스ID,
    대분류명,
    소분류명,
    서비스상태,
    서비스명
)
VALUES (%s, %s, %s, %s, %s, %s)
'''

In [17]:
# DataFrame 데이터를 MySQL에 저장
data_to_insert = [
    tuple(row)
    for row in df.itertuples(
        index=False,
        name=None
    )
]

cursor.executemany(
    insert_sql,
    data_to_insert
)

conn.commit()

print('데이터 저장 완료')
print('저장 데이터:', cursor.rowcount, '건')

데이터 저장 완료
저장 데이터: 18 건

## 데이터 저장 결과 확인

MySQL 테이블에 저장된 데이터의 개수를 조회하여
정상적으로 저장되었는지 확인한다.

In [18]:
# 저장된 데이터 개수 확인
cursor.execute(
    f'SELECT COUNT(*) FROM {table_name}'
)

count = cursor.fetchone()[0]

print('MySQL 저장 데이터:', count, '건')

MySQL 저장 데이터: 18 건

## 데이터 조회 및 검증

MySQL에 저장된 체육시설 데이터를 SELECT 문으로 조회하고
Pandas DataFrame으로 변환하여 확인한다.

In [19]:
# MySQL 데이터 조회

select_sql = f'''
SELECT
    서비스구분,
    서비스ID,
    대분류명,
    소분류명,
    서비스상태,
    서비스명
FROM {table_name}
'''

cursor.execute(select_sql)

rows = cursor.fetchall()

db_df = pd.DataFrame(
    rows,
    columns=[
        '서비스구분',
        '서비스ID',
        '대분류명',
        '소분류명',
        '서비스상태',
        '서비스명'
    ]
)

display(db_df)

,서비스구분,서비스ID,대분류명,소분류명,서비스상태,서비스명
0,자체,S210401100008601453,체육시설,축구장,접수종료,○ [평일] (주간) 마포 난지천 인조잔디축구장
1,자체,S241210095552925088,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
2,자체,S241210100011131040,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
3,자체,S241210100257966783,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
4,자체,S241210100509852746,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)
5,자체,S241210100804518772,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(주간사용)
6,자체,S241210100945082970,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(조기사용)
7,자체,S250113101314920195,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(야간사용)
8,자체,S250113101640215242,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(주간사용)
9,자체,S250113101818758665,체육시설,풋살장,접수종료,잠실제3풋살경기장-토/일/공휴일(조기사용)
10,자체,S250113102023294415,체육시설,풋살장,접수종료,잠실제3풋살경기장-평일(야간사용)
11,자체,S251121100349891778,체육시설,테니스장,접수중,테니스장1(평일)-2026년 응봉공원(대현산배수지)
12,자체,S251121102355938084,체육시설,테니스장,접수중,테니스장1(토/일/공휴일)-2026년 응봉공원(대현산배수지)
13,자체,S251121103012746640,체육시설,테니스장,접수중,테니스장2(평일)-2026년 응봉공원(대현산배수지)
14,자체,S251121103347587479,체육시설,테니스장,접수중,테니스장2(토/일/공휴일)-2026년 응봉공원(대현산배수지)
15,자체,S251121103722953401,체육시설,다목적경기장,접수중,다목적구장-2026년 응봉공원(대현산배수지)
16,자체,S260706132614891677,체육시설,풋살장,접수중,8월 [평일]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수
17,자체,S260706134128763150,체육시설,풋살장,접수중,8월 [공휴일주말]월드컵난지천공원 풋살장 대여 - 7월15일(수) 오후1시 접수

In [20]:
# CSV와 MySQL 데이터 개수 비교
csv_count = len(df)
db_count = len(db_df)

print('CSV 데이터:', csv_count, '건')
print('MySQL 데이터:', db_count, '건')

if csv_count == db_count:
    print('데이터 저장 검증 성공')
else:
    print('데이터 저장 검증 실패')

CSV 데이터: 18 건
MySQL 데이터: 18 건
데이터 저장 검증 성공

## MySQL 연결 종료

데이터 저장 및 검증이 완료되었으므로
MySQL 연결을 종료한다.

In [21]:
# MySQL 연결 종료
cursor.close()
conn.close()

print('MySQL 연결 종료 완료')

MySQL 연결 종료 완료